link to the docs source file in Github on each docs page
paketo-buildpacks/paketo-website pull request #109
Opened 2021-02-25 21:42 UTC by fg-j

## Summary

Resolves #104 . It's not the prettiest thing, but it is functional. Happy to field suggestions on a better UX.

## Use Cases

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.

2021-02-25 22:02 UTC, ForestEckhardt commented
I think that I am going to defer on this one to @kvedurmu. I think that a button would look nicer and be less intrusive. But I am not married to that idea.

2021-02-26 15:30 UTC, kvedurmu commented
Yeah. I agree with @ForestEckhardt that we should include a button called "Edit" and link straight to the edit page for the individual docs. The buttons on buildpacks.io (e.g https://buildpacks.io/docs/) look really good, and maybe we can re-use that and just style it to paketo colors.

2021-02-26 19:29 UTC, fg-j commented
@kvedurmu I gave it a shot. Let me know what you think. I rebased on Forest's changes so it's easier to get a sense of what it'd really look like. @ForestEckhardt it seems like you have a bit more CSS finesse. Maybe There's a better way to do this that I just didn't figure out.

2021-03-01 14:44 UTC, kvedurmu commented
This button looks great @fg-j. As I mentioned in https://github.com/paketo-buildpacks/paketo-website/pull/110#issuecomment-786777784, I think we should get a designer to look at the updated header, so it could be simpler to separate this from Forest's PR.

2021-03-01 14:58 UTC, fg-j commented
@kvedurmu I'll wait until @ForestEckhardt updates the PR to extract the header work. Because I still want this one to take advantage of the improved link styling and stuff.

2021-03-01 15:46 UTC, kvedurmu commented
@fg-j Forest's PR has been merged into main, so you can go ahead and rebase off of that.

2021-03-01 15:48 UTC, kvedurmu requested changes
It looks like the "Edit" text is not lined up with the Github icon. Another suggestion I'd make is to create a box around this so that it stands out more on the page. See this [buildpacks.io example](https://buildpacks.io/docs/) for reference
 
![image](https://user-images.githubusercontent.com/37810054/109521606-7b1d0e80-7a7b-11eb-87f9-a4af0ddb5ee5.png)

2021-03-01 16:00 UTC, kvedurmu commented on layouts/partials/docs-body.html
> +              <a href="http://github.com/paketo-buildpacks/paketo-website/edit/main/content/{{ .File.Path }}" target="_blank" class=edit></a>
Is it possible to also add this button to the bottom of the page?

2021-03-03 22:31 UTC, fg-j commented
Closing because this is addressed in #111

2021-03-03 22:31 UTC, closed without merging