Adds documentation about Node Start detection and start command priority
paketo-buildpacks/paketo-website pull request #76
Opened 2020-12-04 16:41 UTC by ForestEckhardt

2020-12-04 19:02 UTC, arjun024 requested changes

2020-12-04 19:02 UTC, arjun024 commented on content/docs/buildpacks/language-family-buildpacks/nodejs.md
> +The Node.js CNB allows you to build a Node.js app that does not relay on any
```suggestion
The Node.js CNB allows you to build a Node.js app that does not rely on any
```

2020-12-04 22:44 UTC, kvedurmu approved these changes

2020-12-07 15:00 UTC, arjun024 approved these changes

2020-12-07 15:00 UTC, merged