Update Python howto to explain conda solver selection
paketo-buildpacks/paketo-website pull request #762
Opened 2024-02-07 09:15 UTC by sgaist

## Summary

This PR documents how to change the default conda solver to use mamba following the merge of https://github.com/paketo-buildpacks/miniconda/pull/480.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2024-02-07 16:29 UTC, arjun024 approved these changes

2024-02-07 16:32 UTC, arjun024 requested changes

2024-02-07 16:32 UTC, arjun024 commented on content/docs/howto/python.md
> +as nummber of channels configured, package pinning precision, etc. This is an
```suggestion
as number of channels configured, package pinning precision, etc. This is an
```

2024-02-07 16:32 UTC, arjun024 commented
Thanks @sgaist for the docs

2024-02-07 18:07 UTC, sgaist commented on content/docs/howto/python.md
> +as nummber of channels configured, package pinning precision, etc. This is an
Done

2024-02-08 22:33 UTC, arjun024 approved these changes

2024-02-08 22:48 UTC, ForestEckhardt approved these changes

2024-02-08 22:49 UTC, merged